services:
  database:
    container_name: noob_store_db
    image: postgres
    restart: always

    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - default

  server:
    container_name: noob_store
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    environment:
      - GIN_MODE=release
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - default

volumes:
  data:

networks:
  default:
    driver: bridge
